### ISSUE TITLE
Organization: Relocate Tricky Concepts

### ISSUE THREAD

**Issue by jesseilev** [Launch-Code/cs50x-live-2016#79]
Get rid of those notes, figure out where to stash them.

Also, do we want faculty guides?

**Comment by jesseilev** [comment]
Where did we put that stuff?? Anybody know?

**Comment by newjoiner** [comment]
## Tricky Concepts / Things to Emphasize

* multiple files: first time they've seen a program composed of multiple files working together
.h files for declaring public interface
   * [Module 3 Class 2 Prep / Resource: Spread Out](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/resources/spread-out)
   * [Module 3 Class 2 Prep / Exercise: Delmar House of Tires](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/exercises/spread-out)
* creating and writing to arrays / have to declare the size first
   * [Module 2 Class 2 Prep / Resource: Array Basics](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/resources/array-basics)
* functions (TODO they actually have seen this stuff the prevous week, so re-look over the below:)
   * first time theyve seen a program that implements its own functions, rather than just a big fat main()
      * [Module 2 Class 1 Prep / Resource: Writing Your Own Function](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/resources/our-own-functions)
      * [Module 2 Class 1 Prep / Lecture Notes Functions and Arguments](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/class1-prep#functions)
   * **I can't find a resource explaining implementation vs invocation, but there is a resource for return statements**
   * understanding the two different roles: implementation vs invocation
   * implementation
      * (usually) have to declare the signature
      * return statement - [Module 3 Class 1 Prep / Return Statements Halt Execution](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/resources/return-halts-execution) 
      * terminates execution early
   * invocation
      * understand that the body of the function is just "sitting there patiently", does not run until your call it from elsewhere

**Comment by jesseilev** [comment]
This issue was moved to LaunchCodeEducation/cs50x-live#57
